(define (problem pb1)
    	(:domain monkeyproblem)
  	(:objects p1 p2 p3 bananas monkey box)
  	(:init (location p1)
		(location p2)
		(location p3)
	 	(at monkey p1)
		(on-floor)
		(at box p2)
		(at bananas p3)
	)
  	(:goal (and (hasbananas)))
)